language: python
python:
    - "3.9"
install:
    - pip install -r requirements.txt
    - pip install .
script:
    - bash ls -lash
    - bash ls -lash blaseball-stlats-tlracker
    - bash ls -lash tests
    - python tests/tests.py
